services:
  mcp-doc:
    build:
      context: .
    container_name: mcp-doc
    restart: unless-stopped
    env_file:
      - .env
    environment:
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
      AZURE_OPENAI_ENDPOINT: ${AZURE_OPENAI_ENDPOINT}
    networks:
      - webproxy
    expose:
      - "9001"
    labels:
      # Activation de Traefik
      - "traefik.enable=true"
      
      # Configuration du routeur principal
      - "traefik.http.routers.mcp-doc.rule=Host(`mcp.documentation.thibaultbriand.fr`)"
      - "traefik.http.routers.mcp-doc.entrypoints=websecure"
      - "traefik.http.routers.mcp-doc.tls.certresolver=myresolver"
      
      # Configuration du service
      - "traefik.http.services.mcp-doc.loadbalancer.server.port=9001"
      - "traefik.http.services.mcp-doc.loadbalancer.server.scheme=http"
      
      # Spécifier le réseau pour Traefik
      - "traefik.docker.network=webproxy"
      
      # Middleware pour les headers SSE (optionnel)
      - "traefik.http.middlewares.mcp-doc-headers.headers.customResponseHeaders.Cache-Control=no-cache"
      - "traefik.http.middlewares.mcp-doc-headers.headers.customResponseHeaders.Connection=keep-alive"
      - "traefik.http.routers.mcp-doc.middlewares=mcp-doc-headers"

networks:
  webproxy:
    external: true